
# Developer id
DEVELOPER_CHAT_ID = 943373513


# user states
NEW_USER: str = 'NewUser'
LANGUAGE_GOT: str = 'LanguageGot'
CODE_SENT: str = 'CodeSent'
PHONE_CONFIRMED: str = 'PhoneConfirmed'
ACTIVE_USER: str = 'ActiveUser'


# states
(
    REGISTRATION,
    LANGUAGE,
    PHONE_CONFIRMATION,
    PHONE_CODE,
    NAME_INPUT,
    REGISTRATION_END,
    MAIN_MENU,
    STATE_SETTINGS,
    CHANGING_LANGUAGE,
    CHANGING_NAME,
    CHANGING_PHONE,
    MAIN_SHOPPING,
    CHECKING_PH_CODE,
    EXIT_SHOPPING,
    QUITTING_ADMIN_PANEL,
    ADMIN_MAIN,
    ADDING_ITEMS,
    ADD_ITEM_NAME,
    ADD_ITEM_PRICE,
    ADD_ITEM_DESCRIPTION,
    ADD_ITEM_CATEGORY,
    ADD_ITEM_QUANTITY
) = range(22)
